"""add updated_at column to play_games

Revision ID: 3285ba2dc3e9
Revises: ffcd9425bea6
Create Date: 2025-04-30 03:57:49.574446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3285ba2dc3e9'
down_revision = 'ffcd9425bea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_games', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
