"""update default value of timestamp

Revision ID: c146075316a6
Revises: 
Create Date: 2025-04-21 04:58:09.170062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c146075316a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_games')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rule', sa.String(length=100), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_id', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('rule')
        batch_op.drop_column('title')

    op.create_table('_alembic_tmp_games',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.Column('game_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=5), nullable=True),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rule', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
