"""add signup_data column to games

Revision ID: ffcd9425bea6
Revises: c7f1f5be53cb
Create Date: 2025-04-30 01:31:12.468240

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone

# revision identifiers, used by Alembic.
revision = 'ffcd9425bea6'
down_revision = 'c7f1f5be53cb'
branch_labels = None
depends_on = None


# migrations/versions/xxx_fix_signup_data.py

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_games', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    
    # 手动添加部分：为已有记录设置默认值
    op.execute(
        sa.text("UPDATE play_games SET updated_at = :now WHERE updated_at IS NULL"),
        {'now': datetime.now(timezone.utc)}
    )
    
    # 修改列为NOT NULL
    op.alter_column('play_games', 'updated_at',
                   existing_type=sa.DateTime(timezone=True),
                   nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play_games', 'updated_at')
    # ### end Alembic commands ###